/* CREATE TABLE audio_features(
    id_audio INTEGER PRIMARY KEY AUTOINCREMENT,
    id_persona CHAR(36),
    mfcc_1  FLOAT NOT NULL,         
    mfcc_2  FLOAT NOT NULL,
    mfcc_3  FLOAT NOT NULL,
    mfcc_4  FLOAT NOT NULL,
    mfcc_5  FLOAT NOT NULL,
    mfcc_6  FLOAT NOT NULL,
    mfcc_7  FLOAT NOT NULL,
    mfcc_8  FLOAT NOT NULL,
    mfcc_9  FLOAT NOT NULL,
    mfcc_10 FLOAT NOT NULL, 
    mfcc_11 FLOAT NOT NULL, 
    mfcc_12 FLOAT NOT NULL, 
    mfcc_13 FLOAT NOT NULL, 
    mfcc_14 FLOAT NOT NULL, 
    mfcc_15 FLOAT NOT NULL, 
    mfcc_16 FLOAT NOT NULL, 
    mfcc_17 FLOAT NOT NULL, 
    mfcc_18 FLOAT NOT NULL,   
    mfcc_19 FLOAT NOT NULL,
    mfcc_20 FLOAT NOT NULL, 
    mfcc_21 FLOAT NOT NULL, 
    mfcc_22 FLOAT NOT NULL, 
    mfcc_23 FLOAT NOT NULL, 
    mfcc_24 FLOAT NOT NULL, 
    mfcc_25 FLOAT NOT NULL, 
    mfcc_26 FLOAT NOT NULL, 
    mfcc_27 FLOAT NOT NULL, 
    mfcc_28 FLOAT NOT NULL, 
    mfcc_29 FLOAT NOT NULL, 
    mfcc_30 FLOAT NOT NULL, 
    mfcc_31 FLOAT NOT NULL, 
    mfcc_32 FLOAT NOT NULL, 
    mfcc_33 FLOAT NOT NULL, 
    mfcc_34 FLOAT NOT NULL, 
    mfcc_35 FLOAT NOT NULL, 
    mfcc_36 FLOAT NOT NULL, 
    mfcc_37 FLOAT NOT NULL, 
    mfcc_38 FLOAT NOT NULL, 
    mfcc_39 FLOAT NOT NULL, 
    mfcc_40 FLOAT NOT NULL,
    FOREIGN KEY (id_persona) REFERENCES personas(id_persona)
); */

/* CREATE TABLE personas(
    id_persona CHAR(36) PRIMARY KEY,
    nombre CHAR(15),
    genero INTEGER(1) check (genero in (0, 1)),
    navegador CHAR(20) check (navegador in ('firefox', 'chrome')),
    correo CHAR(50)
);  */
